name: Tests

on: [push]

jobs:
  test-app:
  runs-on: macos-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Setup Node.js
    uses: actions/setup-node@v1
    with:
      node-version: '14.x'

  - name: Install dependencies
    run: set -x
    run: npm install

  - name: Run tests
    run: npm test
